version: '3.1'

services:
  nginx:
    image: nginx:1.15.3
    container_name: nginx
    ports:
      - "41080:80"
    volumes: 
      - static:/opt/services/activation_portal/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - activation_portal_app    

  postgresql:
    image: postgres:11
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 

  activation_portal_app:
    container_name: activation_portal_app
    command: ./start.sh
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - static:/opt/services/activation_portal/static
    depends_on: 
      - postgresql

volumes: 
  pgdata: {}
  static: {}